ignore_all_files_in_gitignore: true
ignored_paths: []
read_only: false
excluded_tools: []
initial_prompt: ""
project_name: "rusl.myx.is"
base_modes:
default_modes:
included_optional_tools: []
fixed_tools: []
encoding: utf-8
languages:
- typescript
